site_name: awesome 中文詩歌
site_url: https://awesome-zh-hymns.web.app/
theme:
  name: material
  language: zh-TW
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/awchjimmy/awesome-zh-hymns
repo_name: awchjimmy/awesome-zh-hymns
